server:
  port: 8081

spring:
  application:
    name: test-service-provider

eureka:
  client:
    service-url:
      defaultZone: http://root:123@localhost:9091/eureka/,http://root:123@localhost:9092/eureka/,

alpha:
  cluster:
    address: 192.168.1.20

management:
  endpoints:
    web:
      exposure:
        include: "*"


